"""add_credit_ledger_table

Revision ID: 12e638fbc565
Revises: 9285c2232240
Create Date: 2026-09-08 12:30:33.355738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e638fbc565'
down_revision: Union[str, None] = '9285c2232240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('spot_content_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', name='uq_credit_ledger_user_source')
    )
    op.create_index(op.f('ix_credit_ledger_created_at'), 'credit_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_ledger_spot_content_id'), 'credit_ledger', ['spot_content_id'], unique=False)
    op.create_index(op.f('ix_credit_ledger_user_id'), 'credit_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_ledger_user_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_spot_content_id'), table_name='credit_ledger')
    op.drop_index(op.f('ix_credit_ledger_created_at'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    # ### end Alembic commands ###
