"""add_notifications_tables

기능 8(질문/답변 알림) 신규 테이블 3개:

- `notifications`      알림 이벤트 1건. 행 자체가 발송 로그를 겸한다(별도 push_log 없음).
- `user_notification_settings`  사용자당 1행 **전역** 알림 스위치. 기존 관광지별
                       `spot_notification_settings`(기능 3)와는 별개이며 기본값이 반대(ON)다.
                       행이 없는 것이 정상이며 그때는 코드의 기본값(True)으로 동작하므로,
                       기존 사용자에 대한 백필 INSERT를 하지 않는다.
- `push_subscriptions` **이번 범위에서는 아무도 쓰지 않는다.** Web Push/FCM을 나중에 붙일 때를
                       위해 컬럼 모양만 미리 못박아 둔 빈 테이블이다(P18). 채널 중립 이름이라
                       `device_tokens`/`fcm_token` 같은 벤더 종속 이름을 쓰지 않았다.

타입은 String/Boolean/DateTime/Text만 써서 SQLite(로컬)·PostgreSQL(Railway) 양쪽에서 그대로 돈다.
배포 시에는 Dockerfile의 `alembic upgrade head`로 자동 적용된다.

Revision ID: 1d90a3fa7298
Revises: c924ebb93d39
Create Date: 2026-09-10 21:39:07.991978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d90a3fa7298'
down_revision: Union[str, None] = 'c924ebb93d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('spot_content_id', sa.String(length=20), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_spot_content_id'), 'notifications', ['spot_content_id'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_spot_type', 'notifications', ['user_id', 'spot_content_id', 'type'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('keys_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='uq_push_subscription_user_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_notification_setting_user')
    )
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_notifications_user_spot_type', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_spot_content_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
