"""add_bookmarks_table

Revision ID: 263b3684e281
Revises: 12e638fbc565
Create Date: 2026-09-08 18:37:59.217962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263b3684e281'
down_revision: Union[str, None] = '12e638fbc565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spot_content_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_content_id', name='uq_bookmark_user_spot')
    )
    op.create_index(op.f('ix_bookmarks_created_at'), 'bookmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookmarks_spot_content_id'), 'bookmarks', ['spot_content_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_spot_content_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_created_at'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
