"""add questions and answers tables

Revision ID: 9285c2232240
Revises: a1b2c3d4e5f6
Create Date: 2026-08-31 16:30:45.100064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9285c2232240'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spot_content_id', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('answer_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_spot_content_id'), 'questions', ['spot_content_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('gps_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_created_at'), 'answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_created_at'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_spot_content_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
