"""add_presences_table

Revision ID: c924ebb93d39
Revises: 263b3684e281
Create Date: 2026-09-09 16:01:08.517993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c924ebb93d39'
down_revision: Union[str, None] = '263b3684e281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('spot_content_id', sa.String(length=20), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'spot_content_id', name='uq_presence_user_spot')
    )
    op.create_index(op.f('ix_presences_last_seen'), 'presences', ['last_seen'], unique=False)
    op.create_index(op.f('ix_presences_spot_content_id'), 'presences', ['spot_content_id'], unique=False)
    op.create_index(op.f('ix_presences_user_id'), 'presences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presences_user_id'), table_name='presences')
    op.drop_index(op.f('ix_presences_spot_content_id'), table_name='presences')
    op.drop_index(op.f('ix_presences_last_seen'), table_name='presences')
    op.drop_table('presences')
    # ### end Alembic commands ###
